module.exports = [
  {
    ignores: ['node_modules/**', 'index.html', '.worktrees/**', 'desktop/dist/**', 'desktop/src-tauri/target/**', 'desktop/src-tauri/gen/**'],
  },
  {
    files: ['**/*.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'commonjs',
      globals: {
        require: 'readonly',
        module: 'writable',
        process: 'readonly',
        console: 'readonly',
        __dirname: 'readonly',
        Buffer: 'readonly',
        Blob: 'readonly',
        URL: 'readonly',
        // Text in, bytes out (and back) -- both are globals in Node and in the
        // browser, which is what lets the same decode rule run in either.
        TextDecoder: 'readonly',
        TextEncoder: 'readonly',
        URLSearchParams: 'readonly',
        fetch: 'readonly',
        AbortController: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
      },
    },
    rules: {
      'no-unused-vars': 'warn',
      'no-undef': 'error',
    },
  },
  {
    // Loaded into the page by a <script> tag rather than required, so these are
    // the browser's globals and not a typo. Listed per file rather than added to
    // every file, because a node module reaching for `document` really is a bug.
    files: ['transcript-controller.js'],
    languageOptions: {
      globals: {
        window: 'readonly',
        document: 'readonly',
        requestAnimationFrame: 'readonly',
      },
    },
  },
  {
    // Also loaded by a <script> tag: the picture index is the browser's own
    // storage, which node has no form of (the tests pass a stand-in instead).
    files: ['image-store.js'],
    languageOptions: {
      globals: {
        indexedDB: 'readonly',
      },
    },
  },
  {
    // The Puter SDK bridge: it exists to drive a browser SDK, so `document` and
    // `FileReader` are the point rather than a mistake. Everything it does is
    // behind a `loaded()` check, so in node it reports "not loaded" instead of
    // reaching for either.
    files: ['desktop/src/puter.js'],
    languageOptions: {
      globals: {
        document: 'readonly',
        FileReader: 'readonly',
      },
    },
  },
  {
    // HF auth uses browser crypto and localStorage for the OAuth flow.
    files: ['desktop/src/hf-auth.js'],
    languageOptions: {
      globals: {
        window: 'readonly',
        localStorage: 'readonly',
        crypto: 'readonly',
        btoa: 'readonly',
        fetch: 'readonly',
      },
    },
  },
  {
    // Remote handoff opens an EventSource for SSE streaming from the engine.
    files: ['desktop/src/remote-handoff.js'],
    languageOptions: {
      globals: {
        EventSource: 'readonly',
      },
    },
  },
  {
    // Main app script loaded via <script> in index.html -- hundreds of browser
    // globals, so declare the common ones explicitly rather than letting every
    // use of `document` or `window` be a false positive.
    files: ['app.js'],
    languageOptions: {
      globals: {
        window: 'readonly',
        document: 'readonly',
        navigator: 'readonly',
        self: 'readonly',
        caches: 'readonly',
        btoa: 'readonly',
        atob: 'readonly',
        XMLSerializer: 'readonly',
        Image: 'readonly',
        WebSocket: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        ResizeObserver: 'readonly',
        createImageBitmap: 'readonly',
        ClipboardItem: 'readonly',
        confirm: 'readonly',
        prompt: 'readonly',
        mermaid: 'readonly',
        event: 'readonly',
        location: 'readonly',
        localStorage: 'readonly',
        requestAnimationFrame: 'readonly',
        fetch: 'readonly',
        URL: 'readonly',
        Blob: 'readonly',
        FormData: 'readonly',
        File: 'readonly',
        FileReader: 'readonly',
        crypto: 'readonly',
        sessionStorage: 'readonly',
        history: 'readonly',
        screen: 'readonly',
        CustomEvent: 'readonly',
        Event: 'readonly',
        HTMLElement: 'readonly',
        Element: 'readonly',
        Node: 'readonly',
        NodeList: 'readonly',
        HTMLCollection: 'readonly',
        DocumentFragment: 'readonly',
        Text: 'readonly',
        Comment: 'readonly',
        MutationObserver: 'readonly',
        IntersectionObserver: 'readonly',
        PerformanceObserver: 'readonly',
        requestIdleCallback: 'readonly',
        cancelIdleCallback: 'readonly',
        structuredClone: 'readonly',
        Performance: 'readonly',
        DOMParser: 'readonly',
        Range: 'readonly',
        Selection: 'readonly',
        getComputedStyle: 'readonly',
        scrollTo: 'readonly',
        scrollBy: 'readonly',
        open: 'readonly',
        close: 'readonly',
        postMessage: 'readonly',
        addEventListener: 'readonly',
        removeEventListener: 'readonly',
        dispatchEvent: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        console: 'readonly',
        Math: 'readonly',
        Date: 'readonly',
        JSON: 'readonly',
        Promise: 'readonly',
        Object: 'readonly',
        Array: 'readonly',
        String: 'readonly',
        Number: 'readonly',
        Boolean: 'readonly',
        RegExp: 'readonly',
        Error: 'readonly',
        Map: 'readonly',
        Set: 'readonly',
        WeakMap: 'readonly',
        WeakSet: 'readonly',
        Symbol: 'readonly',
        parseInt: 'readonly',
        parseFloat: 'readonly',
        isNaN: 'readonly',
        isFinite: 'readonly',
        encodeURI: 'readonly',
        encodeURIComponent: 'readonly',
        decodeURI: 'readonly',
        decodeURIComponent: 'readonly',
        // Globals from other script files loaded in index.html before app.js
        DEFAULT_MODEL: 'readonly',
        DEFAULT_EFFORT: 'readonly',
        PUTER_PROVIDER: 'readonly',
        isValidMode: 'readonly',
        DEFAULT_MODE: 'readonly',
        NeuraOSCommandState: 'readonly',
        MODES: 'readonly',
        TOOL_GROUPS: 'readonly',
        MODE_TOOL_GROUPS: 'readonly',
        WRITE_TOOL_GROUPS: 'readonly',
        CHAT_COMMANDS: 'readonly',
        SKILL_CREATOR_PROMPT: 'readonly',
        extractMessageText: 'readonly',
        parseSkillDraft: 'readonly',
        addUserSkill: 'readonly',
        safeJson: 'readonly',
        normalizeSkillUsage: 'readonly',
        recordSkillPin: 'readonly',
        suggestSkillFor: 'readonly',
        MAX_ACTIVE_SKILLS: 'readonly',
        deactivateSkill: 'readonly',
        activateSkill: 'readonly',
        resolveChatCommand: 'readonly',
        renderCommandsHelp: 'readonly',
        renderSkillsCommandReply: 'readonly',
        isValidModel: 'readonly',
        supportsEffort: 'readonly',
        EFFORT_LEVELS: 'readonly',
        needsPuterAccount: 'readonly',
        escapeHtml: 'readonly',
        isGithubWriteTool: 'readonly',
        describeToolCall: 'readonly',
        normalizeWorkspacePath: 'readonly',
        workspaceList: 'readonly',
        workspaceRead: 'readonly',
        workspaceSearch: 'readonly',
        MAX_WORKSPACE_SEARCH_MATCHES: 'readonly',
        workspaceWrite: 'readonly',
        workspaceEdit: 'readonly',
        workspaceDelete: 'readonly',
        normalizeTaskGraph: 'readonly',
        newTaskGraph: 'readonly',
        renderTaskGraphText: 'readonly',
        addTask: 'readonly',
        setTaskStatus: 'readonly',
        orderTodos: 'readonly',
        todoProgress: 'readonly',
        renderTodoSummary: 'readonly',
        toggleTodoStatus: 'readonly',
        routeClassifier: 'readonly',
        routeStep: 'readonly',
        refusedModelIds: 'readonly',
        describeRoute: 'readonly',
        imageBackendOrder: 'readonly',
        failoverProviderOrder: 'readonly',
        MAX_PROVIDER_FAILOVERS: 'readonly',
        nextFailoverProvider: 'readonly',
        nearestUsableModel: 'readonly',
        modelForImage: 'readonly',
        MAX_IMAGE_EDGE: 'readonly',
        isSendableImageUrl: 'readonly',
        MAX_IMAGE_DATA_URL_CHARS: 'readonly',
        usableChatModels: 'readonly',
        MAX_MODEL_REFUSAL_RETRIES: 'readonly',
        RATE_LIMIT_BASE_DELAY_MS: 'readonly',
        isQuotaExhausted: 'readonly',
        isRetryableStatus: 'readonly',
        isRateLimitError: 'readonly',
        errorDetailFromBody: 'readonly',
        isModelScopedRefusal: 'readonly',
        parseSseChunk: 'readonly',
        cachedTokensFromUsage: 'readonly',
        renderSkillsPrompt: 'readonly',
        memoryPromptFor: 'readonly',
        renderTaskGraphPrompt: 'readonly',
        SYSTEM_PROMPT: 'readonly',
        modePrompt: 'readonly',
        workspacePrompt: 'readonly',
        compactChatHistory: 'readonly',
        buildChatHistory: 'readonly',
        isEffortUnsupportedError: 'readonly',
        modeBlocksWrite: 'readonly',
        modeWriteRefusal: 'readonly',
        isGithubTool: 'readonly',
        isWebTool: 'readonly',
        isMcpTool: 'readonly',
        mcpTool: 'readonly',
        MCP_LIST_TOOLS: 'readonly',
        isRunTool: 'readonly',
        isWorkspaceTool: 'readonly',
        isTaskTool: 'readonly',
        isUseSkillTool: 'readonly',
        MEMORY_TOOL: 'readonly',
        createReadMemory: 'readonly',
        parsePendingTurn: 'readonly',
        serializePendingTurn: 'readonly',
        pendingTurnStepCount: 'readonly',
        toolCallRecords: 'readonly',
        hasToolWork: 'readonly',
        GITHUB_TOOLS: 'readonly',
        toolRoundsForMode: 'readonly',
        callStage: 'readonly',
        isToolsRejection: 'readonly',
        extractToolCalls: 'readonly',
        textToolCalls: 'readonly',
        withTextToolCalls: 'readonly',
        extractMessageReasoning: 'readonly',
        EMPTY_REPLY_NUDGE: 'readonly',
        todoReportNudge: 'readonly',
        toConversationMessage: 'readonly',
        isTaskWriteTool: 'readonly',
        planToolCalls: 'readonly',
        toolArgsUnusable: 'readonly',
        toolCallKey: 'readonly',
        parseToolArgs: 'readonly',
        MAX_REPEATED_TOOL_CALLS: 'readonly',
        batchIndices: 'readonly',
        REPEATED_TOOL_CALL_NOTICE: 'readonly',
        routedStepFailure: 'readonly',
        clipToolResult: 'readonly',
        TOOL_ROUNDS_EXHAUSTED_PROMPT: 'readonly',
        lastImageInMessages: 'readonly',
        imageAction: 'readonly',
        imageSizeFromPrompt: 'readonly',
        imageSizeBody: 'readonly',
        STREAM_RENDER_MIN_MS: 'readonly',
        nextStreamCadence: 'readonly',
        puter: 'readonly',
        resolveImageAction: 'readonly',
        isVisionCapable: 'readonly',
        DEFAULT_VISION_MODEL: 'readonly',
        WEB_TOOLS: 'readonly',
        WORKSPACE_TOOLS: 'readonly',
        TASK_TOOLS: 'readonly',
        RUN_TOOLS: 'readonly',
        toolsForMode: 'readonly',
        learnedSkillNames: 'readonly',
        skillsForTurn: 'readonly',
        filterToolsBySkills: 'readonly',
        modeAllowsTool: 'readonly',
        USE_SKILL_TOOL: 'readonly',
        RESUME_CONTINUATION_PROMPT: 'readonly',
        isFailoverWorthyFailure: 'readonly',
        flattenToolTurn: 'readonly',
        withImageTurn: 'readonly',
        IMAGE_PLANNER_PROMPT: 'readonly',
        parseImagePlan: 'readonly',
        isModerationRefusal: 'readonly',
        isOutOfCreditsError: 'readonly',
        isAccountLevelFailure: 'readonly',
        IMAGE_QUALITY: 'readonly',
        IMAGE_REFUSAL_ADVICE: 'readonly',
        imageFailureMessage: 'readonly',
        imageMediaType: 'readonly',
        imageCheckFixPrompt: 'readonly',
        imageDownloadFormat: 'readonly',
        buildImagePdf: 'readonly',
        imageDownloadFilename: 'readonly',
        IMAGE_DOWNLOAD_FORMATS: 'readonly',
        renderMarkdownLite: 'readonly',
        CanvasArtifacts: 'readonly',
        CANVAS_REACT_MARKER: 'readonly',
        openSelectedCanvasBlock: 'readonly',
        announcesUnread: 'readonly',
        shouldFollowTranscript: 'readonly',
        transcriptAtBottom: 'readonly',
        parseAppLink: 'readonly',
        freeRowsOnly: 'readonly',
        MODELS: 'readonly',
        describeProviderModel: 'readonly',
        placeDropdown: 'readonly',
        ATTACH_MENU_WIDTH: 'readonly',
        ATTACH_MENU_MIN_HEIGHT: 'readonly',
        ATTACH_MENU_MAX_HEIGHT: 'readonly',
        selectAttachKind: 'readonly',
        pdfjsLib: 'readonly',
        mammoth: 'readonly',
        handleFileSelect: 'readonly',
        attachmentKindFor: 'readonly',
        decodeAttachmentText: 'readonly',
        describeAttachmentCost: 'readonly',
        HISTORY_TOKEN_BUDGET: 'readonly',
        setAutoRetry: 'readonly',
        setFreeModelsOnly: 'readonly',
        jumpToSettingsSection: 'readonly',
        openPaletteFromDrawer: 'readonly',
        stripStoredImages: 'readonly',
        capConversationImages: 'readonly',
        MAX_MESSAGES_PER_CONVERSATION: 'readonly',
        upsertConversation: 'readonly',
        deriveChatTitle: 'readonly',
        migrateLegacyMessages: 'readonly',
        sortConversations: 'readonly',
        retryTargetFor: 'readonly',
        memoryUseMeter: 'readonly',
        addMemoryFactFromInput: 'readonly',
        clearAllMemoryFacts: 'readonly',
        openDrawer: 'readonly',
        refreshPage: 'readonly',
        shareConversation: 'readonly',
        providerHealthState: 'readonly',
        testAllProviders: 'readonly',
        setReasoningVisible: 'readonly',
        clearTaskList: 'readonly',
        setRoutingEnabled: 'readonly',
        setMaskBrush: 'readonly',
        clearMask: 'readonly',
        submitImageEdit: 'readonly',
        copyLightboxImage: 'readonly',
        copyConversation: 'readonly',
        conversationToMarkdown: 'readonly',
        forkConversation: 'readonly',
        handleAuthClick: 'readonly',
        githubLoadFile: 'readonly',
        githubCommit: 'readonly',
        designCreateProject: 'readonly',
        designGenerate: 'readonly',
        designExport: 'readonly',
        designCloseEditor: 'readonly',
        designSaveCurrent: 'readonly',
        copyShareLink: 'readonly',
        revokeShareLink: 'readonly',
        setMemoryForChat: 'readonly',
        setSkillsEnabled: 'readonly',
        cycleMode: 'readonly',
        selectEffort: 'readonly',
        focusEffort: 'readonly',
        handleKeyDown: 'readonly',
        toggleAttachMenu: 'readonly',
        reasoningTailLine: 'readonly',
        describeReasoning: 'readonly',
        ShareMemory: 'readonly',
        sharePayloadOf: 'readonly',
        memoryFactsUsedIn: 'readonly',
        shareImageDataUrlFactory: 'readonly',
        NeuraOSTranscript: 'readonly',
        isValidEffort: 'readonly',
        normalizeProviderReply: 'readonly',
        explainEmptyReply: 'readonly',
        estimateCostWarning: 'readonly',
        describeDrawnSize: 'readonly',
        reframePlan: 'readonly',
        imageRatioLabel: 'readonly',
        imageModelsFor: 'readonly',
        imageRatioBody: 'readonly',
        acceptsImages: 'readonly',
        NeuraOSProviderRouting: 'readonly',
        IMAGE_CHECK_PROMPT: 'readonly',
        imageCheckQuestion: 'readonly',
        parseImageCheck: 'readonly',
        storedImagePlan: 'readonly',
        imageStoreAvailable: 'readonly',
        putImageBytes: 'readonly',
        readImageBytes: 'readonly',
        pruneImageBytes: 'readonly',
        STORED_IMAGE_MAX_EDGE: 'readonly',
        STORED_IMAGE_MAX_CHARS: 'readonly',
      },
    },
  },
  {
    // Canvas artifacts module: uses document via injected deps, not globals.
    // No browser globals needed at module scope (it's an IIFE with deps injection).
    files: ['canvas-artifacts.js'],
    languageOptions: {
      globals: {},
    },
  },
  {
    // Inline diffs: DOM manipulation, uses document
    files: ['inline-diffs.js'],
    languageOptions: {
      globals: {
        document: 'readonly',
      },
    },
  },
  {
    // Live presence: WebSocket, document, window, setInterval
    files: ['live-presence.js'],
    languageOptions: {
      globals: {
        document: 'readonly',
        window: 'readonly',
        WebSocket: 'readonly',
        setInterval: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        fetch: 'readonly',
      },
    },
  },
  {
    // Live preview: document, window
    files: ['live-preview.js'],
    languageOptions: {
      globals: {
        document: 'readonly',
        window: 'readonly',
        Blob: 'readonly',
        URL: 'readonly',
      },
    },
  },
  {
    // Magnetic effects: document
    files: ['magnetic-effects.js'],
    languageOptions: {
      globals: {
        document: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
      },
    },
  },
  {
    // Mermaid canvas: document, window, mermaid, prompt, confirm, Image, XMLSerializer, btoa
    files: ['mermaid-canvas.js'],
    languageOptions: {
      globals: {
        document: 'readonly',
        window: 'readonly',
        mermaid: 'readonly',
        prompt: 'readonly',
        confirm: 'readonly',
        Image: 'readonly',
        XMLSerializer: 'readonly',
        btoa: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        fetch: 'readonly',
      },
    },
  },
  {
    // Rich context menus: document, window, navigator, confirm
    files: ['rich-context-menus.js'],
    languageOptions: {
      globals: {
        document: 'readonly',
        window: 'readonly',
        navigator: 'readonly',
        confirm: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
      },
    },
  },
  {
    // Service worker: self, caches
    files: ['sw.js'],
    languageOptions: {
      globals: {
        self: 'readonly',
        caches: 'readonly',
        fetch: 'readonly',
        Promise: 'readonly',
        Response: 'readonly',
        Request: 'readonly',
      },
    },
  },
  {
    // Performance module: IntersectionObserver, Worker and rAF-gated lazy
    // effects -- all browser-only, loaded via <script> like the rest.
    files: ['performance-optimized.js'],
    languageOptions: {
      globals: {
        document: 'readonly',
        window: 'readonly',
        requestAnimationFrame: 'readonly',
        cancelAnimationFrame: 'readonly',
        MutationObserver: 'readonly',
        IntersectionObserver: 'readonly',
        Worker: 'readonly',
      },
    },
  },
];
