// NeuraOS design tokens -> the files each app reads (docs/neuraos-rebrand-plan.md, R0).
//
// design/tokens.json is the one source of truth. This turns it into:
//   design/tokens.css                                   CSS variables (web, desktop)
//   android/app/src/main/java/com/neura/os/app/ui/Tokens.kt   Compose colours, shapes, motion
//
// No dependencies. test/tokens.test.js runs render() and fails when a generated
// file on disk differs from it, so an edit to tokens.json that nobody
// regenerated cannot ship, and it checks every text colour against WCAG AA.
//
// Usage:  npm run tokens          write both files
//         node scripts/tokens.js --check   exit 1 when either is stale

'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const SOURCE = path.join(ROOT, 'design', 'tokens.json');
const CSS_OUT = path.join(ROOT, 'design', 'tokens.css');
const KOTLIN_OUT = path.join(ROOT, 'android', 'app', 'src', 'main', 'java', 'com', 'neura', 'os', 'app', 'ui', 'Tokens.kt');

const HEX = /^#[0-9A-Fa-f]{6}$/;
const HEADER = 'GENERATED by scripts/tokens.js from design/tokens.json -- do not edit; run `npm run tokens`.';

function readTokens(file = SOURCE) {
  return JSON.parse(fs.readFileSync(file, 'utf8'));
}

/** The named values of one group, in file order, skipping $-keys. */
function entries(group) {
  return Object.keys(group || {})
    .filter((key) => !key.startsWith('$'))
    .map((key) => [key, group[key].$value]);
}

function themes(tokens) {
  const out = {};
  for (const [theme, group] of Object.entries(tokens.color || {})) {
    if (theme.startsWith('$')) continue;
    out[theme] = entries(group);
    for (const [name, value] of out[theme]) {
      if (!HEX.test(value)) throw new Error(`color.${theme}.${name} is not a #RRGGBB colour: ${value}`);
    }
  }
  const names = (list) => list.map(([name]) => name).join(',');
  if (!out.dark || !out.light) throw new Error('tokens.json needs color.dark and color.light');
  if (names(out.dark) !== names(out.light)) throw new Error('color.dark and color.light must name the same colours, in the same order');
  return out;
}

function px(value) {
  const match = /^(\d+(?:\.\d+)?)px$/.exec(String(value));
  if (!match) throw new Error(`not a px dimension: ${value}`);
  return Number(match[1]);
}

function ms(value) {
  const match = /^(\d+)ms$/.exec(String(value));
  if (!match) throw new Error(`not a ms duration: ${value}`);
  return Number(match[1]);
}

const kebab = (name) => name.replace(/[A-Z]/g, (c) => '-' + c.toLowerCase());
const upperSnake = (name) => name.replace(/[A-Z]/g, (c) => '_' + c).toUpperCase();

function renderCss(tokens) {
  const all = themes(tokens);
  const vars = (list) => list.map(([name, value]) => `  --neura-${kebab(name)}: ${value.toUpperCase()};`).join('\n');
  const radius = entries(tokens.radius).map(([name, value]) => `  --neura-radius-${kebab(name)}: ${px(value)}px;`).join('\n');
  const motion = entries(tokens.motion)
    .filter(([, value]) => typeof value === 'string')
    .map(([name, value]) => `  --neura-motion-${kebab(name)}: ${ms(value)}ms;`).join('\n');
  return [
    `/* ${HEADER} */`,
    '',
    ':root,',
    '[data-theme="dark"] {',
    '  color-scheme: dark;',
    vars(all.dark),
    radius,
    motion,
    '}',
    '',
    '[data-theme="light"] {',
    '  color-scheme: light;',
    vars(all.light),
    '}',
    '',
  ].join('\n');
}

function renderKotlin(tokens) {
  const all = themes(tokens);
  const fields = all.dark.map(([name]) => `    val ${name}: Color,`).join('\n');
  const values = (list) => list.map(([name, value]) => `        ${name} = Color(0xFF${value.slice(1).toUpperCase()}),`).join('\n');
  const radius = entries(tokens.radius).map(([name, value]) => `    const val RADIUS_${upperSnake(name)} = ${px(value)}`).join('\n');
  const motion = entries(tokens.motion).map(([name, value]) => {
    if (typeof value === 'number') return `    const val ${upperSnake(name)} = ${value}f`;
    return `    const val ${upperSnake(name)}_MS = ${ms(value)}`;
  }).join('\n');
  return [
    `// ${HEADER}`,
    'package com.neura.os.app.ui',
    '',
    'import androidx.compose.runtime.Immutable',
    'import androidx.compose.ui.graphics.Color',
    '',
    '/** One theme\'s colours. Read through [Palette], which picks the theme. */',
    '@Immutable',
    'class NeuraColors(',
    fields,
    ')',
    '',
    '/** NeuraOS design tokens (docs/neuraos-rebrand-plan.md). */',
    'object NeuraTokens {',
    '    val Dark = NeuraColors(',
    values(all.dark),
    '    )',
    '',
    '    val Light = NeuraColors(',
    values(all.light),
    '    )',
    '',
    radius,
    motion,
    '}',
    '',
  ].join('\n');
}

function render(tokens = readTokens()) {
  return { [CSS_OUT]: renderCss(tokens), [KOTLIN_OUT]: renderKotlin(tokens) };
}

// --- WCAG contrast, for the test ------------------------------------------------

function luminance(hex) {
  const channel = (i) => {
    const c = parseInt(hex.slice(i, i + 2), 16) / 255;
    return c <= 0.03928 ? c / 12.92 : Math.pow((c + 0.055) / 1.055, 2.4);
  };
  return 0.2126 * channel(1) + 0.7152 * channel(3) + 0.0722 * channel(5);
}

function contrast(a, b) {
  const [hi, lo] = [luminance(a), luminance(b)].sort((x, y) => y - x);
  return (hi + 0.05) / (lo + 0.05);
}

module.exports = { render, renderCss, renderKotlin, readTokens, themes, contrast, CSS_OUT, KOTLIN_OUT };

if (require.main === module) {
  const files = render();
  const check = process.argv.includes('--check');
  let stale = 0;
  for (const [file, text] of Object.entries(files)) {
    const rel = path.relative(ROOT, file);
    const current = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : null;
    if (current === text) continue;
    if (check) {
      stale += 1;
      console.error('stale: ' + rel);
    } else {
      fs.mkdirSync(path.dirname(file), { recursive: true });
      fs.writeFileSync(file, text);
      console.log('wrote ' + rel);
    }
  }
  if (stale) process.exit(1);
}
