// GENERATED by scripts/tokens.js from design/tokens.json -- do not edit; run `npm run tokens`.
package com.neura.os.app.ui

import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color

/** One theme's colours. Read through [Palette], which picks the theme. */
@Immutable
class NeuraColors(
    val bg: Color,
    val surface: Color,
    val raised: Color,
    val line: Color,
    val text: Color,
    val muted: Color,
    val accent: Color,
    val onAccent: Color,
    val accentSoft: Color,
    val accentDeep: Color,
    val glow: Color,
    val success: Color,
    val warning: Color,
    val danger: Color,
    val info: Color,
    val code: Color,
)

/** NeuraOS design tokens (docs/neuraos-rebrand-plan.md). */
object NeuraTokens {
    val Dark = NeuraColors(
        bg = Color(0xFF0A0B10),
        surface = Color(0xFF12141B),
        raised = Color(0xFF1A1D26),
        line = Color(0xFF6B7385),
        text = Color(0xFFECEEF4),
        muted = Color(0xFF9AA1B2),
        accent = Color(0xFF8B6CFF),
        onAccent = Color(0xFF1B0F4D),
        accentSoft = Color(0xFF241C4A),
        accentDeep = Color(0xFF4C35C4),
        glow = Color(0xFF22D3EE),
        success = Color(0xFF3FB950),
        warning = Color(0xFFE3B341),
        danger = Color(0xFFF85149),
        info = Color(0xFF58A6FF),
        code = Color(0xFF07080C),
    )

    val Light = NeuraColors(
        bg = Color(0xFFFAFAFB),
        surface = Color(0xFFFFFFFF),
        raised = Color(0xFFEEF0F4),
        line = Color(0xFF7A8396),
        text = Color(0xFF0E1116),
        muted = Color(0xFF525A6B),
        accent = Color(0xFF6D4DF2),
        onAccent = Color(0xFFFFFFFF),
        accentSoft = Color(0xFFECE7FF),
        accentDeep = Color(0xFFD9D0FF),
        glow = Color(0xFF0891B2),
        success = Color(0xFF1A7F37),
        warning = Color(0xFF9A6700),
        danger = Color(0xFFCF222E),
        info = Color(0xFF0969DA),
        code = Color(0xFFF3F4F7),
    )

    const val RADIUS_SM = 8
    const val RADIUS_MD = 12
    const val RADIUS_LG = 16
    const val RADIUS_XL = 24
    const val SPRING_STIFFNESS = 380f
    const val SPRING_DAMPING = 0.8f
    const val FAST_MS = 150
    const val PULSE_MS = 1600
}
