// GENERATED by scripts/tokens.js from design/tokens.json -- do not edit; run `npm run tokens`.
package com.neura.os.app.ui

import androidx.compose.ui.graphics.Color

/** NeuraOS design tokens (docs/neuraos-rebrand-plan.md). Read through [Palette]. */
object NeuraTokens {
    object Dark {
        val bg = Color(0xFF0A0B10)
        val surface = Color(0xFF12141B)
        val raised = Color(0xFF1A1D26)
        val line = Color(0xFF6B7385)
        val text = Color(0xFFECEEF4)
        val muted = Color(0xFF9AA1B2)
        val accent = Color(0xFF8B6CFF)
        val onAccent = Color(0xFF1B0F4D)
        val accentSoft = Color(0xFF241C4A)
        val glow = Color(0xFF22D3EE)
        val success = Color(0xFF3FB950)
        val warning = Color(0xFFE3B341)
        val danger = Color(0xFFF85149)
        val info = Color(0xFF58A6FF)
        val code = Color(0xFF07080C)
    }

    object Light {
        val bg = Color(0xFFFAFAFB)
        val surface = Color(0xFFFFFFFF)
        val raised = Color(0xFFEEF0F4)
        val line = Color(0xFF7A8396)
        val text = Color(0xFF0E1116)
        val muted = Color(0xFF525A6B)
        val accent = Color(0xFF6D4DF2)
        val onAccent = Color(0xFFFFFFFF)
        val accentSoft = Color(0xFFECE7FF)
        val glow = Color(0xFF0891B2)
        val success = Color(0xFF1A7F37)
        val warning = Color(0xFF9A6700)
        val danger = Color(0xFFCF222E)
        val info = Color(0xFF0969DA)
        val code = Color(0xFFF3F4F7)
    }

    const val RADIUS_SM = 8
    const val RADIUS_MD = 12
    const val RADIUS_LG = 16
    const val RADIUS_XL = 24
    const val SPRING_STIFFNESS = 380f
    const val SPRING_DAMPING = 0.8f
    const val FAST_MS = 150
    const val PULSE_MS = 1600
}
